# Generated by Django 2.1.1 on 2019-07-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('file', models.FileField(null=True, upload_to='documents')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bar',
            name='foo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Foo'),
        ),
    ]
