# Generated by Django 2.1.1 on 2019-07-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customer_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='_country',
            new_name='country',
        ),
    ]
