# Generated by Django 2.1.1 on 2019-07-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customer_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='_region',
            new_name='region',
        ),
    ]
