# Generated by Django 2.1.1 on 2019-07-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_customer_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='_city',
            new_name='city',
        ),
    ]
