# Generated by Django 2.2.4 on 2019-08-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190721_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('can_report', 'Can report'),)},
        ),
    ]
