# Generated by Django 2.2.4 on 2019-08-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190814_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('can_report_1', 'Report # 1'), ('can_report_2', 'Report # 2'))},
        ),
    ]
