# Generated by Django 2.1.1 on 2018-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
